# Generated by Django 4.1.11 on 2023-12-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_calmsongs_audio_file_alter_calmsongs_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CsvFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
            ],
        ),
        migrations.DeleteModel(
            name="CalmSongs",
        ),
        migrations.DeleteModel(
            name="HappySongs",
        ),
        migrations.DeleteModel(
            name="MotivationalSongs",
        ),
        migrations.DeleteModel(
            name="SadSongs",
        ),
    ]
