# Generated by Django 4.1.11 on 2023-12-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_employeedetails_performance_taskallocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskallocation",
            name="completed_in",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskallocation",
            name="task_given",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
