# Generated by Django 4.1.11 on 2023-12-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_performance_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performance",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
