# Generated by Django 4.1.11 on 2023-12-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_performance_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                ("deadline", models.DateField()),
                ("dependencies", models.JSONField(default=list)),
                ("resource_availability", models.IntegerField()),
                ("team_performance", models.FloatField()),
                ("actual_completion_time", models.IntegerField()),
            ],
        ),
    ]
